apiVersion: v1
kind: Service
metadata:
  name: nginx-service-blue
spec:
  type: ExternalName
  externalName: service-nginx-color.blue.svc.cluster.local
  #<nome_do_service>.<nome_do_namespace>.svc.cluster.local