version: '3.7'

volumes:
  mongorpws_vol:
  pgsqlrpws_vol:

networks:
  rpws_net:
    driver: bridge

services:
  rpwsapp:
    image: "alexandrebunn/rotten-potatoes-ms:${RPMS_VERSION:?err}"
    container_name: rpwsapp
    ports:
      - 5000:5000
    networks:
      - rpws_net
    depends_on:
      - movie
      - review
    environment:
      MOVIE_SERVICE_URI: http://movie:8181
      REVIEW_SERVICE_URI: http://review:80

  movie:
    image: "alexandrebunn/movie:${MOVIEAPP_VERSION:?err}"
#    ports:
#      - 8081:8081
    networks:
      - rpws_net
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongouser:mongopwd@mongodb:27017/admin

  mongodb:
    image: "mongo:${MONGO_VERSION}"
    container_name: mongorpws
    ports:
      - 27017:27017
    networks:
      - rpws_net
    volumes:
      - mongorpws_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      MONGO_INITDB_ROOT_DATABASE: admin

  review:
    image: "alexandrebunn/review:${REVIEWAPP_VERSION:?err}"
#    ports:
#      - 80:80
    networks:
      - rpws_net
    depends_on:
      - pgsql
    environment:
      ConnectionStrings__MyConnection: Host=pgsql;Database=postgres;Username=postgres;Password=mysecretpassword;

  pgsql:
    image: "postgres:${POSTGRES_VERSION:?err}"
    container_name: pgsqlrpws
    ports:
      - 5432:5432
    networks:
      - rpws_net
    volumes:
      - pgsqlrpws_vol:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mysecretpassword
