version: '3.8'

volumes:
  mongorpws_vol:
  pgsqlrpws_vol:

networks:
  rpws_net:
    driver: bridge

services:
  rpws:
    image: alexandrebunn/rotten-potatoes:v1
    ports:
      - 5000:5000
    networks:
      - rpws_net
    depends_on:
      - movie
      - review
    environment:
      MOVIE_SERVICE_URI: http://movies:8181
      REVIEW_SERVICE_URI: http://review:8282

  movie:
    image: alexandrebunn/movie:${MOVIEAPP_VERSION:?err}
    ports:
      - 8081:8081
    networks:
      - rpws_net
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongoadmin:secret@mongodb:27017/admin

  mongodb:
    image: mongo:${MONGO_VERSION:?err}
    container_name: mongorpws
    ports:
      - 27017:27017
    networks:
      - rpws_net
    volumes:
      - mongorrpws_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      MONGO_INITDB_ROOT_DATABASE: admin

  review:
    image: alexandrebunn/review:${REVIEWAPP_VERSION:?err}
    ports:
      - 8282:80
    networks:
      - rpws_net
    depends_on:
      - pgsql
    environment:
      ConnectionStrings__MyConnection: Host=pgsql;Database=postgres;Username=postgres;Password=mysecretpassword;

  pgsql:
    image: mongo:${PGSQL_VERSION:?err}
    container_name: pgsqlrpws
    ports:
      - 5432:5432
    networks:
      - rpws_net
    volumes:
      - pgsqlrpws_vol:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mysecretpassword
